# Generated by Django 5.1.6 on 2025-02-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_sortie', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Band',
        ),
    ]
