# Generated by Django 5.1.6 on 2025-03-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_last_sorties_remove_film_date_sortie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Last_sorties',
        ),
        migrations.AddField(
            model_name='film',
            name='date_sortie',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='duree',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
