# Generated by Django 5.1.6 on 2025-03-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_delete_last_sorties_film_date_sortie_film_duree'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='synopsis',
            field=models.URLField(blank=True, null=True),
        ),
    ]
