# Generated by Django 5.1.6 on 2025-03-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_film_genre_film_synopsis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='date_sortie',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
