# Generated by Django 5.1.6 on 2025-03-19 16:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_film_date_sortie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='date_sortie',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2026)]),
        ),
    ]
