# Generated by Django 5.1.6 on 2025-03-27 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_film_date_sortie'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='mois_sortie',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
