# Generated by Django 5.1.6 on 2025-04-17 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_film_mois_sortie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='film',
            unique_together={('name', 'date_sortie')},
        ),
        migrations.CreateModel(
            name='UserFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('VU', 'Vu'), ('A_VOIR', 'À voir')], default='A_VOIR', max_length=6)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('film', 'user')},
            },
        ),
    ]
