# Generated by Django 5.1.6 on 2025-04-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_remove_film_mois_sortie'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='statut',
            field=models.CharField(choices=[('VU', 'Vu'), ('AVOIR', 'À voir')], default='AVOIR', max_length=6),
        ),
        migrations.DeleteModel(
            name='UserFilm',
        ),
    ]
